### ISSUE TITLE
5.internal-document-search が Application Error で動作しない（CosmosDBのロール割り当て不足？）

### ISSUE THREAD

**Issue by mkht** [Azure-Samples/jp-azureopenai-samples#76]
5.internal-document-search のサンプルをREADMEの記載通りにデプロイし、デプロイはエラーなく成功したもののアプリにアクセスすると Application Error で正常動作していない。

kuduのLog streamでログを確認するとCosmosDBの権限不足？のようなエラーが発生している。
```
Request is blocked because principal <GUID> does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [dbs/****]. Learn more: https://aka.ms/cosmos-native-rbac.
```

以下のQiita記事を参考に、CosmosDBの組み込みロール`Cosmos DB Built-in Data Contributor`をManaged IDに付与することでエラーが解消し、アプリが動作するようになった。
https://qiita.com/coitate/items/a0e4df2d330b4f488cd0

具体的にはAz CLIを用いて以下のコマンドを実行した。
```
az cosmosdb sql role assignment create --account-name <CosmosDB名> --resource-group  <ResourceGroup名> --scope "/" --principal-id <エラーログに記録されているPrincipalID> --role-definition-id /subscriptions/<subscription-id>/resourceGroups/<ResouceGroup名>/providers/Microsoft.DocumentDB/databaseAccounts/<CosmodDB名>/sqlRoleDefinitions/00000000-0000-0000-0000-000000000002
```

おそらくBicepを使ってこのロール割り当てを自動化することができると思うが、自分がBicepについて無知なのでそこまではできなかった。

**Comment by rukasakurai** [comment]
azdコマンドはazure.yamlの定義に従って実行されます。5章のazure.yamlではpostprovisionを使ってAzureリソースのプロビジョニング後にprepdocs.ps1またはprepdocs.shを呼び出しています。
https://github.com/Azure-Samples/jp-azureopenai-samples/blob/a57c7323e2799d53e47178303399716023e94a9d/5.internal-document-search/azure.yaml#L24

prepdocs.ps1やprepdocs.shで、Cosmos DB用の権限設定をしています。
predocs.ps1の場合:
https://github.com/Azure-Samples/jp-azureopenai-samples/blob/a57c7323e2799d53e47178303399716023e94a9d/5.internal-document-search/scripts/prepdocs.ps1#L19
prepdocs.shの場合:
https://github.com/Azure-Samples/jp-azureopenai-samples/blob/a57c7323e2799d53e47178303399716023e94a9d/5.internal-document-search/scripts/prepdocs.sh#L14

azure.yamlやprepdocs.ps1/shを変更せずに、READMEの手順通りに進めると権限設定も自動的に行われ、ご指摘いただいたエラーは発生せずにアプリケーションは正常に動作するはずですが、例えばazure.yamlのpostprovision部分をコメントアウトしている場合は記載いただいているエラーが発生します。
