### ISSUE TITLE
wrong illustration in `5.internal-document-search` > `internal deployment`

### ISSUE THREAD

**Issue by richardvinc** [Azure-Samples/jp-azureopenai-samples#79]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report 
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
minor issue: in internal deployment section on `5.internal-document-search`, it is illustrated that `app-service-private-endpoint` is on the `sub-app-{resource token}` subnet, but in the `main.bicep` file, it looks like that `appServicePrivateEndopoint` is using `privateEndpointLocation` for its location.

### Expected/desired behavior
> maybe it is more suitable for the illustration to put `app-service-private-endpoint` in the `sub-private-endpoint-{resource token}` subnet instead (or change the code, whichever is easier).

**Comment by kazuki-komori** [comment]
@richardvinc 
Thanks for your report!
There was an error in the architecture diagram as you mentioned.
This issue fixed in PR #90.
