### ISSUE TITLE
There are typos in some documents

### ISSUE THREAD

**Issue by tfukumori** [Azure-Samples/jp-azureopenai-samples#80]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
The following typos appear in these documents
"Azure Form Recgonizer"

https://github.com/search?q=repo%3AAzure-Samples%2Fjp-azureopenai-samples%20Azure%20Form%20Recgonizer&type=code

targets:
https://github.com/Azure-Samples/jp-azureopenai-samples/blob/main/5.internal-document-search/README.md
https://github.com/Azure-Samples/jp-azureopenai-samples/blob/main/5.internal-document-search/deploy_private_endpoint_ennabled.md

reference:
https://learn.microsoft.com/en-us/azure/architecture/ai-ml/architecture/automate-document-processing-azure-form-recognizer

### Expected/desired behavior
Can you please correct the following typo?
"Azure Form Recgonizer" -> "Azure Form Recognizer"

**Comment by kazuki-komori** [comment]
@tfukumori 
Thanks for the report. This Issue has been fixed in #91.
